#!/bin/sh


timedatectl set-timezone Europe/Stockholm
cp mountusb /root
cp umountusb /root

apt-get update
add-apt-repository ppa:jean-francois-dockes/upnpp1 -y
apt-get install python3 python3-pip python-pip python3-setuptools mpd mpc upmpdcli upmpdcli-tidal squeezelite minidlna autoconf make i2c-tools python3-dev python-dev python3-smbus python-mpd -y --allow-unauthenticated -y --allow-unauthenticated
cp mpd.conf /etc/mpd.conf
mv /etc/upmpdcli.conf /etc/upmpdcli.conf.orig
cp upmpdcli.conf /etc/upmpdcli.conf
cp minidlna.conf /etc/minidlna.conf
mv /etc/init.d/squeezelite /etc/squeezelite
cp squeezelite /etc/default/squeezelite
update-rc.d minidlna defaults
cp sun50i-h5-nanopi-neo2-v1.1.dtb /boot/dtb/allwinner
cp armbianEnv.txt /boot

sed -i '$ i echo "4" > /sys/class/gpio/export' /etc/rc.local
sed -i '$ i echo "out" > /sys/class/gpio/gpio4/direction' /etc/rc.local
sed -i '$ i echo "1" > /sys/class/gpio/gpio4/value' /etc/rc.local
sed -i '$ i echo "5" > /sys/class/gpio/export' /etc/rc.local
sed -i '$ i echo "out" > /sys/class/gpio/gpio5/direction' /etc/rc.local
sed -i '$ i echo "1" > /sys/class/gpio/gpio5/value' /etc/rc.local
sed -i '$ i python3 /root/neo2/app.py &' /etc/rc.local
sed -i '$ i bash /root/mountusb &' /etc/rc.local
sed -i '$ i mpc volume 50' /etc/rc.local

pip3 install flask
pip install setuptools
pip install luma.oled

echo
echo "---Insalling roon---"
sleep 3

cd /root
curl -O http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv8.sh
chmod +x roonbridge-installer-linuxarmv8.sh
yes yes | ./roonbridge-installer-linuxarmv8.sh

echo
echo "---Installing OLED---"
sleep 3

cd /root
git clone https://github.com/eragefe/oled_Nanopi_Neo2
cd oled_Nanopi_Neo2
cp oled.service /etc/systemd/system
systemctl enable oled

echo
echo "---Insalling overlayroot---"
sleep 3


echo 
echo "##############################################"
echo                      REBOOT
echo "##############################################"
sleep 2

reboot
