#!/bin/sh


timedatectl set-timezone Europe/Stockholm
cp mountusb /root
cp umountusb /root

apt-get update
add-apt-repository ppa:jean-francois-dockes/upnpp1 -y
apt-get install python-pip python-setuptools mpd mpc upmpdcli upmpdcli-tidal squeezelite minidlna i2c-tools python-dev python-smbus python-mpd python-flask python-wheel libfreetype6-dev libjpeg-dev build-essential -y --allow-unauthenticated
cp mpd.conf /etc/mpd.conf
mv /etc/upmpdcli.conf /etc/upmpdcli.conf.orig
cp upmpdcli.conf /etc/upmpdcli.conf
cp minidlna.conf /etc/minidlna.conf
mv /etc/init.d/squeezelite /etc/squeezelite
cp squeezelite /etc/default/squeezelite
update-rc.d minidlna defaults
#cp sun50i-h5-nanopi-neo-plus2.dtb /boot/dtb/allwinner
#cp armbianEnv.txt /boot

sed -i '$ i python /root/neoplus2/app.py &' /etc/rc.local
sed -i '$ i python /root/neoplus2/oled/oled.py &' /etc/rc.local
sed -i '$ i bash /root/mountusb &' /etc/rc.local
sed -i '$ i mpc volume 66' /etc/rc.local

echo
echo "---Insalling roon---"
sleep 3

cd /root
curl -O http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv8.sh
chmod +x roonbridge-installer-linuxarmv8.sh
yes yes | ./roonbridge-installer-linuxarmv8.sh

echo
echo "---Installing OLED---"
sleep 3

pip install --upgrade luma.oled

ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

echo 
echo "##############################################"
echo                      REBOOT
echo "##############################################"
sleep 2

reboot
