#!/bin/sh


timedatectl set-timezone Europe/Stockholm
cp mountusb /root
cp umountusb /root

apt-get update
add-apt-repository ppa:jean-francois-dockes/upnpp1 -y
apt-get install python-pip python-setuptools mpd mpc upmpdcli upmpdcli-tidal squeezelite minidlna i2c-tools python-dev python-smbus python-mpd python-flask python-wheel libfreetype6-dev libjpeg-dev build-essential -y --allow-unauthenticated -y --allow-unauthenticated
cp mpd.conf /etc/mpd.conf
mv /etc/upmpdcli.conf /etc/upmpdcli.conf.orig
cp upmpdcli.conf /etc/upmpdcli.conf
cp minidlna.conf /etc/minidlna.conf
mv /etc/init.d/squeezelite /etc/squeezelite
cp squeezelite /etc/default/squeezelite
update-rc.d minidlna defaults
cp sun50i-h5-nanopi-neo2-v1.1.dtb /boot/dtb/allwinner
cp armbianEnv.txt /boot
cp www.service /etc/systemd/system
systemctl enable www

sed -i '$ i echo "198" > /sys/class/gpio/export' /etc/rc.local
sed -i '$ i echo "out" > /sys/class/gpio/gpio198/direction' /etc/rc.local
sed -i '$ i echo "1" > /sys/class/gpio/gpio198/value' /etc/rc.local
sed -i '$ i echo "199" > /sys/class/gpio/export' /etc/rc.local
sed -i '$ i echo "out" > /sys/class/gpio/gpio199/direction' /etc/rc.local
sed -i '$ i echo "1" > /sys/class/gpio/gpio199/value' /etc/rc.local
sed -i '$ i bash /root/mountusb &' /etc/rc.local
sed -i '$ i mpc volume 50' /etc/rc.local
sed -i '$ i ifconfig wlan0 up' /etc/rc.local
sed -i '$ i bash /root/wifi' /etc/rc.local

echo
echo "---Insalling roon---"
sleep 3

cd /root
curl -O http://download.roonlabs.com/builds/roonbridge-installer-linuxarmv8.sh
chmod +x roonbridge-installer-linuxarmv8.sh
yes yes | ./roonbridge-installer-linuxarmv8.sh

echo
echo "---Installing OLED---"
sleep 3

cd /root
git clone https://github.com/eragefe/oled_Nanopi_Neo2
cd oled_Nanopi_Neo2
cp oled.service /etc/systemd/system
systemctl enable oled

ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules

echo
echo "---Insalling overlayroot---"
sleep 3

apt-get install overlayroot -y
mv /etc/overlayroot.conf /etc/overlayroot.conf.orig
touch /etc/overlayroot.conf
echo overlayroot="tmpfs" > /etc/overlayroot.conf

echo 
echo "##############################################"
echo                      REBOOT
echo "##############################################"
sleep 2

reboot
